---
services:
  loki:
    image: grafana/loki:3.7.8@sha256:1107dd5274e0ada47e42472b7a7e71f3b2a2fe878878108f3e2f9e51528f0193
    container_name: loki
    volumes:
      - ./loki-config.yaml:/etc/loki/config.yaml
      - ./rules:/rules/fake
      - /mnt/ssd512/ctr_data/loki/data:/data/loki
    user: "9001:9001"
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/config.yaml
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:3100/ready || exit 1
      interval: 1m
      timeout: 10s
      retries: 2
      start_period: 60s
    restart: unless-stopped
  
networks:
  default:
    external: true
    name: ctr-network
