---
services:
  sonarr:
    image: 'ghcr.io/linuxserver/sonarr:4.0.17@sha256:60f3b6b5c7647ba2bafd81163acfe34b11117b9b834ebd7fbcc3e5f1b309c7ef'
    container_name: sonarr
    labels:
      - traefik.enable=true
      - traefik.http.services.sonarr.loadbalancer.server.port=8989
      - show.external=true
    environment:
      - PUID=9001
      - PGID=9001
      - TZ="Australia/Melbourne"
    volumes:
      - './config:/config'
      - '/mnt/data8tb/videos:/tv'
      - '/mnt/data8tb/downloads:/media'
    restart: 'unless-stopped'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8989/sonarr"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 1m
networks:
  default:
    external: true
    name: ctr-network