services:
  wfhdiary:
    image: ghcr.io/acbgbca/ato-wfh-diary:latest@sha256:88687a51379b8a623cd3063882bdc59870fa6b816317a4cb459963538988615d
    container_name: wfhdiary
    user: 9001:9001
    restart: unless-stopped
    environment:
      - FORWARD_AUTH_HEADER=Remote-User
    labels:
      - traefik.enable=true
      - traefik.http.services.wfhdiary.loadbalancer.server.port=8080
      - show.external=true
    volumes:
      - ./data:/data

networks:
  default:
    external: true
    name: ctr-network
