services:
  wfhdiary:
    image: ghcr.io/acbgbca/ato-wfh-diary:latest@sha256:298c599d7cf92239bdf10f22bebf89e16c9b8f163875ef19c4f6eaff0510b97f
    container_name: wfhdiary
    user: 9001:9001
    restart: unless-stopped
    environment:
      - FORWARD_AUTH_HEADER=Remote-User
    labels:
      - traefik.enable=true
      - traefik.http.services.wfhdiary.loadbalancer.server.port=8080
      - show.external=true
    volumes:
      - ./data:/data

networks:
  default:
    external: true
    name: ctr-network
