services:
  wfhdiary:
    image: ghcr.io/acbgbca/ato-wfh-diary:latest@sha256:1f6c3ed81362de2f094a6cb94e76bf08bf110048b2dced77f7f4641a0eed2b84
    container_name: wfhdiary
    user: 9001:9001
    restart: unless-stopped
    environment:
      - FORWARD_AUTH_HEADER=Remote-User
    labels:
      - traefik.enable=true
      - traefik.http.services.wfhdiary.loadbalancer.server.port=8080
      - show.external=true
    volumes:
      - ./data:/data

networks:
  default:
    external: true
    name: ctr-network
