
services:
  prowlarr:
    image: ghcr.io/linuxserver/prowlarr:latest@sha256:c7502a75b021d964481c129c84590b9cbc40f83aadd4e553f173871bc0deaa3c
    container_name: prowlarr
    labels:
      - traefik.enable=true
      - traefik.http.services.prowlarr.loadbalancer.server.port=9696
      - show.external=true
    environment:
      - PUID=9001
      - PGID=9001
      - TZ=Australia/Melbourne
    volumes:
      - ./config:/config
    restart: unless-stopped
networks:
  default:
    external: true
    name: ctr-network
