
services:
  prowlarr:
    image: ghcr.io/linuxserver/prowlarr:latest@sha256:a46d0ce0a8236bc4e065fe7c91a55d026c9d849620c5845250519b977d8857f3
    container_name: prowlarr
    labels:
      - traefik.enable=true
      - traefik.http.services.prowlarr.loadbalancer.server.port=9696
      - show.external=true
    environment:
      - PUID=9001
      - PGID=9001
      - TZ=Australia/Melbourne
    volumes:
      - ./config:/config
    restart: unless-stopped
networks:
  default:
    external: true
    name: ctr-network
