services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v3.28.0@sha256:8b02290f4d1806f02acac6f25f6d48a3c965612fda1f8e914d5af533276f8688
    container_name: mealie
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.services.mealie.loadbalancer.server.port=9000
      - show.external=true
    env_file:
      - mealie.env
    volumes:
      - ./data:/app/data/

networks:
  default:
    external: true
    name: ctr-network
