services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v3.23.1@sha256:5fc5cebedddb3952c1ee78f20faf42ab7e49986813fd314745aa97978a4a13eb
    container_name: mealie
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.services.mealie.loadbalancer.server.port=9000
      - show.external=true
    env_file:
      - mealie.env
    volumes:
      - ./data:/app/data/

networks:
  default:
    external: true
    name: ctr-network
