services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v3.14.0@sha256:b9fac07e6daaabd8c29d0dc97965c2f500ce7d6b188b0c51f494627f23ad32f2
    container_name: mealie
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.services.mealie.loadbalancer.server.port=9000
      - show.external=true
    env_file:
      - mealie.env
    volumes:
      - ./data:/app/data/

networks:
  default:
    external: true
    name: ctr-network
