services:
  apprise:
    image: caronc/apprise:v1.5.2@sha256:feb3ad42d280bca0c58fdff6f77f46e2586a65bbc6d2bff614d31245ff8a399c
    container_name: apprise
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.services.apprise.loadbalancer.server.port=8000
      - show.external=true
    env_file:
      - apprise.env
    volumes:
      - ./config:/config
      - ./attach:/attach
  signal:
    image: bbernhard/signal-cli-rest-api:0.100@sha256:2399d449123cdad56c4d859277e3b9127e1a00c4d2ab4601c239882609286cf8
    container_name: signal
    restart: unless-stopped
    environment:
      - MODE=native
      - AUTO_RECEIVE_SCHEDULE=0 21 * * *
    volumes:
      - ./signal:/home/.local/share/signal-cli

networks:
  default:
    external: true
    name: ctr-network
