services:
  apprise:
    image: caronc/apprise:v2.0.0@sha256:cc5ef662ad2a4a25958f1eddbf87f2e95f9bf637ea481f1adcec18312ad262f5
    container_name: apprise
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.services.apprise.loadbalancer.server.port=8000
      - show.external=true
    env_file:
      - apprise.env
    volumes:
      - ./config:/config
      - ./attach:/attach
  signal:
    image: bbernhard/signal-cli-rest-api:0.101@sha256:2cf09d66a86fdd210e42ee91662216364acc27da1163a8c44167a77ea3a6559a
    container_name: signal
    restart: unless-stopped
    environment:
      - MODE=native
      - AUTO_RECEIVE_SCHEDULE=0 21 * * *
    volumes:
      - ./signal:/home/.local/share/signal-cli

networks:
  default:
    external: true
    name: ctr-network
