services:
  n8n:
    image: ghcr.io/n8n-io/n8n:1.123.30@sha256:fb8b8f908d26bfa51f11ad37438cb0748d980ae7e85c7caf2e51c38336cfd9f5
    container_name: n8n
    labels:
      - traefik.enable=true
      - traefik.http.services.n8n.loadbalancer.server.port=5678
      - show.external=true
    env_file:
      - n8n.env
    volumes:
      - ./data:/home/node/.n8n
    restart: 'unless-stopped'
networks:
  default:
    external: true
    name: ctr-network