services:
  n8n:
    image: ghcr.io/n8n-io/n8n:2.36.4@sha256:e4663e728ecb9444243b4748e3fa903493a2c0c28a6db8f0ccd6ea2118a96ad8
    container_name: n8n
    labels:
      - traefik.enable=true
      - traefik.http.services.n8n.loadbalancer.server.port=5678
      - show.external=true
    env_file:
      - n8n.env
    volumes:
      - ./data:/home/node/.n8n
    restart: 'unless-stopped'
networks:
  default:
    external: true
    name: ctr-network