services:
  n8n:
    image: ghcr.io/n8n-io/n8n:2.26.3@sha256:51ac1d08178e635a593368f0947532990e55c14342ac781c8d77538daae859c8
    container_name: n8n
    labels:
      - traefik.enable=true
      - traefik.http.services.n8n.loadbalancer.server.port=5678
      - show.external=true
    env_file:
      - n8n.env
    volumes:
      - ./data:/home/node/.n8n
    restart: 'unless-stopped'
networks:
  default:
    external: true
    name: ctr-network