---
services:
  sabnzbd:
    image: 'ghcr.io/linuxserver/sabnzbd:5.1.2@sha256:13d4404f1242f819e0cc2e294def5858def251a3609eb59404dad303075a564a'
    container_name: sabnzbd
    labels:
      - traefik.enable=true
      - traefik.http.services.sabnzbd.loadbalancer.server.port=8080
      - show.external=true
    environment:
      - PUID=9001
      - PGID=9001
      - TZ="Australia/Melbourne"
    volumes:
        - './config:/config'
        - '/mnt/data8tb/downloads:/media'
    restart: 'unless-stopped'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/sabnzbd"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
networks:
  default:
    external: true
    name: ctr-network
