services:
  olivetin:
    container_name: olivetin
    image: ghcr.io/olivetin/olivetin:2025.11.25@sha256:6ee4ad8805fe90e1f07a15f4f3f9d90019ad2b036426cab1b132ae19653c7dac
    labels:
      - traefik.enable=true
      - traefik.http.services.olivetin.loadbalancer.server.port=1337
      - show.external=true
    volumes:
      - ./config:/config
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
networks:
  default:
    external: true
    name: ctr-network