services:
  xmltvguide:
    image: ghcr.io/acbgbca/xmltvguide:latest@sha256:98737ee83bbe01e4a68853867fe8c369e54649a1006d4c1d7296a7397d365eab
    container_name: xmltvguide
    user: 9001:9001
    restart: unless-stopped
    environment:
      XMLTV_URL: "http://xmltv.net/xml_files/Melbourne.xml"
      TZ: "Australia/Melbourne"
    labels:
      - traefik.enable=true
      - traefik.http.services.xmltvguide.loadbalancer.server.port=8080
      - show.external=true
    volumes:
      - ./data:/data

networks:
  default:
    external: true
    name: ctr-network
