services:
  xmltvguide:
    image: ghcr.io/acbgbca/xmltvguide:latest@sha256:de69c53a3c6539f508dfbf23dd13e7333d82a4951d455436bb0bbabf833bb2de
    container_name: xmltvguide
    user: 9001:9001
    restart: unless-stopped
    environment:
      XMLTV_URL: "http://xmltv.net/xml_files/Melbourne.xml"
      TZ: "Australia/Melbourne"
      HIDDEN_CHANNELS: "16,17,34,36,44,77,78,200,201,301,302"
      CHANNEL_NAME_STRIP: "Melbourne,Victoria,VIC"
      PLEX_URL: ${PLEX_URL}
      PLEX_EXTERNAL_URL: ${PLEX_EXTERNAL_URL}
      PLEX_TOKEN: ${PLEX_TOKEN}
      PLEX_POLL_INTERVAL: 10m
      LOG_LEVEL: debug
    labels:
      - traefik.enable=true
      - traefik.http.services.xmltvguide.loadbalancer.server.port=8080
      - show.external=true
    volumes:
      - ./data:/data

networks:
  default:
    external: true
    name: ctr-network
