services:
  xmltvguide:
    image: ghcr.io/acbgbca/xmltvguide:latest@sha256:0ce28e9e9b6512a8cca75fafac05832a97d2355d99638b771c217a72b1853655
    container_name: xmltvguide
    user: 9001:9001
    restart: unless-stopped
    environment:
      XMLTV_URL: "http://xmltv.net/xml_files/Melbourne.xml"
      TZ: "Australia/Melbourne"
    labels:
      - traefik.enable=true
      - traefik.http.services.xmltvguide.loadbalancer.server.port=8080
      - show.external=true
    volumes:
      - ./data:/data

networks:
  default:
    external: true
    name: ctr-network
