
# To upgrade the database, see https://acbgbca.github.io/documentation/postgres/
services:
  db18:
    image: postgres:18.3@sha256:78481659c47e862334611ccdaf7c369c986b3046da9857112f3b309114a65fb4
    restart: unless-stopped
    volumes:
      - ./pgdata18:/var/lib/postgresql
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless
    labels:
      - sablier.enable=true
      - sablier.group=paperless

  broker:
    image: redis:8.6.2@sha256:832d7785830f3f4b559300e6191fc914b15642c1935252338825cf4332200148
    restart: unless-stopped
    volumes:
      - ./redisdata:/data
    labels:
      - sablier.enable=true
      - sablier.group=paperless

  paperless:
    image: ghcr.io/paperless-ngx/paperless-ngx:2.20.14@sha256:b89f83345532cfba72690185257eb6c4f92fc2a782332a42abe19c07b7a6595f
    container_name: paperless
    restart: unless-stopped
    # user: 9001:9001
    labels:
      - traefik.enable=true
      - traefik.http.services.paperless.loadbalancer.server.port=8000
      - show.external=true
      - sablier.enable=true
      - sablier.group=paperless
    depends_on:
      - db18
      - broker
      - gotenberg
      - tika
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ./data:/usr/src/paperless/data
      - /mnt/data8tb/onedrive/paperless/media:/usr/src/paperless/media
      - /mnt/data8tb/onedrive/paperless/export:/usr/src/paperless/export
      - /mnt/data8tb/onedrive/paperless/consume:/usr/src/paperless/consume
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db18
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998

  gotenberg:
    image: docker.io/gotenberg/gotenberg:8.31@sha256:f0d86e8a1dbc7b33a5a65cb251d02bb271a48ffa989da3feb5ed7d954fe4d4b3
    restart: unless-stopped
    labels:
      - sablier.enable=true
      - sablier.group=paperless
    # The gotenberg chromium route is used to convert .eml files. We do not
    # want to allow external content like tracking pixels or even javascript.
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"

  tika:
    image: docker.io/apache/tika:3.3.0.0@sha256:2a565f1ea1290bdcb74a7d35957d16a989ed44ef98790dcdcc28121d728fa583
    restart: unless-stopped
    labels:
      - sablier.enable=true
      - sablier.group=paperless

networks:
  default:
    external: true
    name: ctr-network
