---
services:
  grafana:
    image: grafana/grafana-oss:13.0.2@sha256:5dad0df181cb644a14e13617b913b261a54f7d4fd4510721dba420929f35bea2
    container_name: grafana
    user: "9001:9001"
    labels:
      - traefik.enable=true
      - traefik.http.services.grafana.loadbalancer.server.port=3000
      - show.external=true
    environment:
      - GF_AUTH_PROXY_ENABLED=true
      - GF_AUTH_PROXY_HEADER_NAME=REMOTE-USER
      - GF_AUTH_PROXY_HEADERS=Name:REMOTE-NAME Email:REMOTE-EMAIL Groups:REMOTE-GROUPS
      - GF_LOG_LEVEL=warn # Grafana logs way too much at info level
    volumes:
      - ./data:/var/lib/grafana
    restart: unless-stopped
  alloy:
    image: grafana/alloy:v1.16.3@sha256:84b76d56c5943025515438fd45cbb5995386a0260d072c9b671dfd7f539f9c01
    container_name: alloy
    command: run --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
    volumes:
      - ./config.alloy:/etc/alloy/config.alloy
      - ./alloy:/var/lib/alloy/data
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/log:/logs:ro
    restart: unless-stopped
networks:
  default:
    external: true
    name: ctr-network