---
services:
  grafana:
    image: grafana/grafana-oss:12.4.2@sha256:83749231c3835e390a3144e5e940203e42b9589761f20ef3169c716e734ad505
    container_name: grafana
    user: "9001:9001"
    labels:
      - traefik.enable=true
      - traefik.http.services.grafana.loadbalancer.server.port=3000
      - show.external=true
    environment:
      - GF_AUTH_PROXY_ENABLED=true
      - GF_AUTH_PROXY_HEADER_NAME=REMOTE-USER
      - GF_AUTH_PROXY_HEADERS=Name:REMOTE-NAME Email:REMOTE-EMAIL Groups:REMOTE-GROUPS
      - GF_LOG_LEVEL=warn # Grafana logs way too much at info level
    volumes:
      - ./data:/var/lib/grafana
    restart: unless-stopped
  alloy:
    image: grafana/alloy:v1.15.0@sha256:579582bce40049f2e27bd1e445000689c907a41f0495cb0d0c7f65609316ba7c
    container_name: alloy
    command: run --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
    volumes:
      - ./config.alloy:/etc/alloy/config.alloy
      - ./alloy:/var/lib/alloy/data
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/log:/logs:ro
    restart: unless-stopped
networks:
  default:
    external: true
    name: ctr-network