---
services:
  grafana:
    image: grafana/grafana-oss:13.0.1@sha256:0f86bada30d65ef9d0183b90c1e2682ac92d53d95da8bed322b984ea78a4a73a
    container_name: grafana
    user: "9001:9001"
    labels:
      - traefik.enable=true
      - traefik.http.services.grafana.loadbalancer.server.port=3000
      - show.external=true
    environment:
      - GF_AUTH_PROXY_ENABLED=true
      - GF_AUTH_PROXY_HEADER_NAME=REMOTE-USER
      - GF_AUTH_PROXY_HEADERS=Name:REMOTE-NAME Email:REMOTE-EMAIL Groups:REMOTE-GROUPS
      - GF_LOG_LEVEL=warn # Grafana logs way too much at info level
    volumes:
      - ./data:/var/lib/grafana
    restart: unless-stopped
  alloy:
    image: grafana/alloy:v1.15.1@sha256:1f40cf52adda8fab3e058f9347a5d165624ecb9fbc1527769cb744748961940d
    container_name: alloy
    command: run --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
    volumes:
      - ./config.alloy:/etc/alloy/config.alloy
      - ./alloy:/var/lib/alloy/data
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/log:/logs:ro
    restart: unless-stopped
networks:
  default:
    external: true
    name: ctr-network