
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v2.2.0@sha256:753eeb0cc22ab7baad39ed47cbd1aae14e193dd1b264e965f193a9ea1d1e1bdd
    container_name: homepage
    user: 9001:9001
    labels:
      - traefik.enable=true
      - traefik.http.services.homepage.loadbalancer.server.port=3000
      - show.external=true
    environment:
      - HOMEPAGE_ALLOWED_HOSTS=homepage.${externalDomain},homepage.${internalDomain}
    volumes:
      - ./config:/app/config
      - ./images:/app/public/images
    restart: unless-stopped
networks:
  default:
    external: true
    name: ctr-network
