
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v2.1.2@sha256:da9dca9ec258c628146bed1445da0853f2b88f0b10bafd97c091de807c363d60
    container_name: homepage
    user: 9001:9001
    labels:
      - traefik.enable=true
      - traefik.http.services.homepage.loadbalancer.server.port=3000
      - show.external=true
    environment:
      - HOMEPAGE_ALLOWED_HOSTS=homepage.${externalDomain},homepage.${internalDomain}
    volumes:
      - ./config:/app/config
      - ./images:/app/public/images
    restart: unless-stopped
networks:
  default:
    external: true
    name: ctr-network
