
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v1.13.1@sha256:d8d784e5090111b6e4c56dfd90e272d2953a2094e87349f647165df0fa6c4401
    container_name: homepage
    user: 9001:9001
    labels:
      - traefik.enable=true
      - traefik.http.services.homepage.loadbalancer.server.port=3000
      - show.external=true
    environment:
      - HOMEPAGE_ALLOWED_HOSTS=homepage.${externalDomain},homepage.${internalDomain}
    volumes:
      - ./config:/app/config
      - ./images:/app/public/images
    restart: unless-stopped
networks:
  default:
    external: true
    name: ctr-network
