services:
  beets:
    image: lscr.io/linuxserver/beets:2.12.0@sha256:b8765bc96d916e455be26130e90391777098c6549a26c8723b3d40f59c224fcf
    container_name: beets
    user: 9001:9001
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.services.beets.loadbalancer.server.port=8337
      - show.external=true
    environment:
      TZ: "Australia/Melbourne"
    volumes:
      - ./config:/config
      - /mnt/data8tb/music_tagged:/music
      - /mnt/data8tb/downloads:/downloads
      - /mnt/data8tb/music_untagged:/untagged
  slskd:
    image: slskd/slskd:0.26.0@sha256:ecd4026d4f8fb504e2cc55323efa2c1f5b56d20d3686b018249cc36b48ea17a6
    container_name: slskd
    user: 9001:9001
    restart: unless-stopped
    ports:
      - 50300:50300
    labels:
      - traefik.enable=true
      - traefik.http.services.slskd.loadbalancer.server.port=5030
      - show.external=true
    environment:
      - SLSKD_REMOTE_CONFIGURATION=true
    volumes:
      - ./slskd:/app
      - /mnt/data8tb/music_untagged:/downloads
  aurral:
    image: ghcr.io/lklynet/aurral:1.76.51@sha256:cf04da830f6965d9bd27d533eddddb0b3430390efe7b4f6f4338e486d4e3ec94
    container_name: aurral
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.services.aurral.loadbalancer.server.port=3001
      - show.external=true
    environment:
      - PUID=9001
      - PGID=9001
    volumes:
      - /mnt/data8tb/downloads:/app/downloads
      - ./aurral:/app/backend/data
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest@sha256:f60ee67694bc4a218efe0fb2dc0b0021d193ac5f15be2638d17ab4eeb6966946
    container_name: lidarr
    labels:
      - traefik.enable=true
      - traefik.http.services.lidarr.loadbalancer.server.port=8686
      - show.external=true
    environment:
      - PUID=9001
      - PGID=9001
      - TZ=Australia/Melbourne
    volumes:
      - ./lidarr:/config
      - /mnt/data8tb/music:/music
      - '/mnt/data8tb/downloads:/media'
    restart: unless-stopped

networks:
  default:
    external: true
    name: ctr-network
