services:
  beets:
    image: lscr.io/linuxserver/beets:2.12.0@sha256:b4751c91795cdb36e7fca83c8deeb5dd8659eb3f595789437f1e2e5651a4acaa
    container_name: beets
    user: 9001:9001
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.services.beets.loadbalancer.server.port=8337
      - show.external=true
    environment:
      TZ: "Australia/Melbourne"
    volumes:
      - ./config:/config
      - /mnt/data8tb/music_tagged:/music
      - /mnt/data8tb/downloads:/downloads
      - /mnt/data8tb/music_untagged:/untagged
  slskd:
    image: slskd/slskd:0.25.1@sha256:ab9ed50e028b524cefdb7c1dd8ebca368a076e18441ee8ac2326473eb850b4c3
    container_name: slskd
    user: 9001:9001
    restart: unless-stopped
    ports:
      - 50300:50300
    labels:
      - traefik.enable=true
      - traefik.http.services.slskd.loadbalancer.server.port=5030
      - show.external=true
    environment:
      - SLSKD_REMOTE_CONFIGURATION=true
    volumes:
      - ./slskd:/app
      - /mnt/data8tb/music_untagged:/downloads
  aurral:
    image: ghcr.io/lklynet/aurral:1.76.51@sha256:cf04da830f6965d9bd27d533eddddb0b3430390efe7b4f6f4338e486d4e3ec94
    container_name: aurral
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.services.aurral.loadbalancer.server.port=3001
      - show.external=true
    environment:
      - PUID=9001
      - PGID=9001
    volumes:
      - /mnt/data8tb/downloads:/app/downloads
      - ./aurral:/app/backend/data
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest@sha256:1caffbd1e5ad5fe3cf6f63de4aa6941e9d31625b0d7e08b60c6eeb6cf09e3a91
    container_name: lidarr
    labels:
      - traefik.enable=true
      - traefik.http.services.lidarr.loadbalancer.server.port=8686
      - show.external=true
    environment:
      - PUID=9001
      - PGID=9001
      - TZ=Australia/Melbourne
    volumes:
      - ./lidarr:/config
      - /mnt/data8tb/music:/music
      - '/mnt/data8tb/downloads:/media'
    restart: unless-stopped

networks:
  default:
    external: true
    name: ctr-network
