services:
  beets:
    image: lscr.io/linuxserver/beets:2.12.0@sha256:4fcf2a7ce3f3fe2d3f29abe088cf510813d31302f18c987c76f6cb02c0cecc11
    container_name: beets
    user: 9001:9001
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.services.beets.loadbalancer.server.port=8337
      - show.external=true
    environment:
      TZ: "Australia/Melbourne"
    volumes:
      - ./config:/config
      - /mnt/data8tb/music_tagged:/music
      - /mnt/data8tb/downloads:/downloads
      - /mnt/data8tb/music_untagged:/untagged
  slskd:
    image: slskd/slskd:0.25.1@sha256:ab9ed50e028b524cefdb7c1dd8ebca368a076e18441ee8ac2326473eb850b4c3
    container_name: slskd
    user: 9001:9001
    restart: unless-stopped
    ports:
      - 50300:50300
    labels:
      - traefik.enable=true
      - traefik.http.services.slskd.loadbalancer.server.port=5030
      - show.external=true
    environment:
      - SLSKD_REMOTE_CONFIGURATION=true
    volumes:
      - ./slskd:/app
      - /mnt/data8tb/music_untagged:/downloads
  aurral:
    image: ghcr.io/lklynet/aurral:1.76.50@sha256:cfd995e4cdec6a280bbaba212c1809b3c561f2d9899b510bd08b268f1c85b28e
    container_name: aurral
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.services.aurral.loadbalancer.server.port=3001
      - show.external=true
    environment:
      - PUID=9001
      - PGID=9001
    volumes:
      - /mnt/data8tb/downloads:/app/downloads
      - ./aurral:/app/backend/data
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest@sha256:4ac390131993f3104a43c4abed79b8abd3227e2536f7b468877e5f41d9f54da4
    container_name: lidarr
    labels:
      - traefik.enable=true
      - traefik.http.services.lidarr.loadbalancer.server.port=8686
      - show.external=true
    environment:
      - PUID=9001
      - PGID=9001
      - TZ=Australia/Melbourne
    volumes:
      - ./lidarr:/config
      - /mnt/data8tb/music:/music
      - '/mnt/data8tb/downloads:/media'
    restart: unless-stopped

networks:
  default:
    external: true
    name: ctr-network
