
services:
  linkding:
    image: sissbruecker/linkding:1.46.2@sha256:0c0a9a04c7ebd644293c37f98710872fe7cdff0ea1ff7fd9be4d235e4c4678d2
    container_name: linkding
    labels:
      - traefik.enable=true
      - traefik.http.services.linkding.loadbalancer.server.port=9090
      - show.external=true
    env_file: linkding.env
    volumes:
      - ./data:/etc/linkding/data
    restart: unless-stopped
networks:
  default:
    external: true
    name: ctr-network
