
services:
  linkding:
    image: sissbruecker/linkding:1.46.0@sha256:49eff0b0b90c63760fda75e615357a0e55fcb7dc51876f2a0a5dddb958bd3df4
    container_name: linkding
    labels:
      - traefik.enable=true
      - traefik.http.services.linkding.loadbalancer.server.port=9090
      - show.external=true
    env_file: linkding.env
    volumes:
      - ./data:/etc/linkding/data
    restart: unless-stopped
networks:
  default:
    external: true
    name: ctr-network
