
services:
  linkding:
    image: sissbruecker/linkding:1.46.1@sha256:45ab921bb772ea24cb05f36d35853f78c7141d932cdc5b30a39b626830908e27
    container_name: linkding
    labels:
      - traefik.enable=true
      - traefik.http.services.linkding.loadbalancer.server.port=9090
      - show.external=true
    env_file: linkding.env
    volumes:
      - ./data:/etc/linkding/data
    restart: unless-stopped
networks:
  default:
    external: true
    name: ctr-network
