services:
  changedetector:
    image: ghcr.io/dgtlmoon/changedetection.io:latest@sha256:7ce66cb803e08beb238aaf99298c571068ec6a5559b7cc383414e9fcf65ad062
    container_name: changedetector
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.services.changedetector.loadbalancer.server.port=5000
      - show.external=true
    volumes:
      - ./data:/datastore
    environment:
      - PUID=9001
      - PGID=9001
      - USE_X_SETTINGS=1

networks:
  default:
    external: true
    name: ctr-network
