services:
  changedetector:
    image: ghcr.io/dgtlmoon/changedetection.io:latest@sha256:d89d4187221206f7f9f2c7946e7483815db905ca7d122644081aebd5d23ba391
    container_name: changedetector
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.services.changedetector.loadbalancer.server.port=5000
      - show.external=true
    volumes:
      - ./data:/datastore
    environment:
      - PUID=9001
      - PGID=9001
      - USE_X_SETTINGS=1

networks:
  default:
    external: true
    name: ctr-network
