services:
  changedetector:
    image: ghcr.io/dgtlmoon/changedetection.io:latest@sha256:b632a9fb6be702fb859e02cd5cac5de7a7466ce1e97f5f5347a1d012c0720108
    container_name: changedetector
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.services.changedetector.loadbalancer.server.port=5000
      - show.external=true
    volumes:
      - ./data:/datastore
    environment:
      - PUID=9001
      - PGID=9001
      - USE_X_SETTINGS=1

networks:
  default:
    external: true
    name: ctr-network
