---
services:
  calibre:
    image: 'ghcr.io/linuxserver/calibre-web:0.6.26@sha256:4db76b9d9fdf6cf5b899ad77c650f212347030337d890af0e0c56bd0a5463cf8'
    container_name: calibre
    labels:
      - traefik.enable=true
      - traefik.http.services.calibre.loadbalancer.server.port=8083
      - show.external=true
      - sablier.enable=true
      - sablier.group=calibre
    environment:
      - PUID=9001
      - PGID=9001
#      - DOCKER_MODS=linuxserver/mods:universal-calibre
    volumes:
      - './config:/config'
      - '/mnt/data8tb/onedrive/calibre/books:/books'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/login"]
      interval: 2m
      timeout: 15s
      retries: 5
      start_period: 30s
      start_interval: 5s
    restart: 'unless-stopped'
  calibreserver:
    image: 'ghcr.io/linuxserver/calibre:9.9.0@sha256:c8c9a1cd9e5345c1b58ad78f2bf352775d90eee61b1f8e5d81c371a66f0bb228'
    container_name: calibreserver
    labels:
      - traefik.enable=true
      - traefik.http.services.calibreserver.loadbalancer.server.port=8080
      - show.external=true
      - sablier.enable=true
      - sablier.group=calibre
    security_opt:
      - seccomp:unconfined
    environment:
      - PUID=9001
      - PGID=9001
    volumes:
      - './server:/config'
      - '/mnt/data8tb/onedrive/calibre/books:/books'
      - '/mnt/data8tb/onedrive/calibre/import:/import'
    restart: 'unless-stopped'

networks:
  default:
    external: true
    name: ctr-network
