---
services:
  calibre:
    image: 'ghcr.io/linuxserver/calibre-web:0.6.26@sha256:87920663935599355d902c3682525c1630a0fd206dd2945aa7ad5c1119245d23'
    container_name: calibre
    labels:
      - traefik.enable=true
      - traefik.http.services.calibre.loadbalancer.server.port=8083
      - show.external=true
      - sablier.enable=true
      - sablier.group=calibre
    environment:
      - PUID=9001
      - PGID=9001
#      - DOCKER_MODS=linuxserver/mods:universal-calibre
    volumes:
      - './config:/config'
      - '/mnt/data8tb/onedrive/calibre/books:/books'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/login"]
      interval: 2m
      timeout: 15s
      retries: 5
      start_period: 30s
      start_interval: 5s
    restart: 'unless-stopped'
  calibreserver:
    image: 'ghcr.io/linuxserver/calibre:9.6.0@sha256:f6368bd6f8ccd172ce2db8e520a4249cf5ccb90c2631537edc566cf8bf8a53a8'
    container_name: calibreserver
    labels:
      - traefik.enable=true
      - traefik.http.services.calibreserver.loadbalancer.server.port=8080
      - show.external=true
      - sablier.enable=true
      - sablier.group=calibre
    security_opt:
      - seccomp:unconfined
    environment:
      - PUID=9001
      - PGID=9001
    volumes:
      - './server:/config'
      - '/mnt/data8tb/onedrive/calibre/books:/books'
      - '/mnt/data8tb/onedrive/calibre/import:/import'
    restart: 'unless-stopped'

networks:
  default:
    external: true
    name: ctr-network
