---
services:
  minecraft-alpha:
    image: ghcr.io/acbgbca/minecraft-bedrock:alpha@sha256:f15f1fad4defbddc5387ce4985c0108848fe296d3137de99754399e7a1bffa9c
    container_name: minecraft-alpha
    user: 9001:9001
    environment:
      - EULA=TRUE
    volumes:
      - ./config:/config
      - ./worlds:/worlds
    security_opt:
      - no-new-privileges:true
    networks:
      default:
          ipv4_address: 192.168.0.71
networks:
  default:
    name: lan-network
    external: true
