---
services:
  minecraft-alpha:
    image: ghcr.io/acbgbca/minecraft-bedrock:alpha@sha256:4755e79ed24f8c54e361f37bdf8aba730c329f62b33cc6d5d9b02445793a40a1
    container_name: minecraft-alpha
    user: 9001:9001
    environment:
      - EULA=TRUE
    volumes:
      - ./config:/config
      - ./worlds:/worlds
    security_opt:
      - no-new-privileges:true
    networks:
      default:
          ipv4_address: 192.168.0.71
networks:
  default:
    name: lan-network
    external: true
