---
services:
  minecraft-alpha:
    image: ghcr.io/acbgbca/minecraft-bedrock:alpha@sha256:a811649b2024c39057ff5d4f2679a0e0d6ec88ea83c8fd62e2601a0db532abb0
    container_name: minecraft-alpha
    user: 9001:9001
    environment:
      - EULA=TRUE
    volumes:
      - ./config:/config
      - ./worlds:/worlds
    security_opt:
      - no-new-privileges:true
    networks:
      default:
          ipv4_address: 192.168.0.71
networks:
  default:
    name: lan-network
    external: true
