services:
  gluetun:
    image: qmcgaw/gluetun:v3.41.1
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - "8888:8888"   # HTTP proxy port (Tinyproxy, exposed via Gluetun's network)
    env_file: gluetun.env
    volumes:
      - ./data:/gluetun
    restart: unless-stopped

  proxy:
    image: ubuntu/squid:latest
    container_name: squid
    network_mode: "service:gluetun"
    depends_on:
      gluetun:
        condition: service_started # sometimes gluetun takes a while to become healthy. Start proxy anyway
    volumes:
      - ./squid.conf:/etc/squid/squid.conf:ro
    restart: unless-stopped

