services:
  jellyfin:
    image: jellyfin/jellyfin:10.11.11@sha256:aefb67e6a7ff1debdd154a78a7bbb780fd0c873d8639210a7f6a2016ad2b35db
    container_name: jellyfin
    labels:
      - traefik.enable=true
      - traefik.http.services.jellyfin.loadbalancer.server.port=8096
      - show.external=false
    env_file: jellyfin.env
    user: 9001:9001
    volumes:
      - ./config:/config
      - /mnt/ssd512/ctr_data/jellyfin/cache:/cache
      - '/mnt/data8tb/videos:/data'
      - /mnt/ssd512/ctr_data/jellyfin/transcode:/transcode:rw
    restart: 'unless-stopped'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
networks:
  default:
    external: true
    name: ctr-network