---

services:
  ldap:
    image: lldap/lldap:v0.6.3@sha256:2a8454b668c1aba7157e832eab0e242e1e7eb5fb7591d7e7774ba05286511ca8
    container_name: ldap
    labels:
      - traefik.enable=true
      - traefik.http.services.ldap.loadbalancer.server.port=17170
    volumes:
      - "./data:/data"
    environment:
      - UID=9001
      - GID=9001
      - TZ="Australia/Melbourne"
      - LLDAP_JWT_SECRET=$LLDAP_JWT_SECRET
      - LLDAP_LDAP_USER_PASS=$LLDAP_LDAP_USER_PASS
      - LLDAP_LDAP_BASE_DN=$LLDAP_LDAP_BASE_DN
    restart: 'unless-stopped'

networks:
  default:
    external: true
    name: ctr-network
