---
services:
  bazarr:
    image: 'ghcr.io/linuxserver/bazarr:1.5.6@sha256:95f27692c3de6dbe130cd035d342d8138ec74ade7b62cfc52e11ae222c52c855'
    container_name: bazarr
    labels:
      - traefik.enable=true
      - traefik.http.services.bazarr.loadbalancer.server.port=6767
      - show.external=true
    environment:
      - PUID=9001
      - PGID=9001
    volumes:
      - './config:/config'
      - '/mnt/data8tb/videos:/tv'
      - '/mnt/data8tb/videos:/movies'
    restart: 'unless-stopped'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6767"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 1m
networks:
  default:
    external: true
    name: ctr-network