---
services:
  minecraft:
    image: ghcr.io/acbgbca/minecraft-bedrock:1.26.12.2@sha256:05206b1c1035442de604c50a630b6ef642a99bc866579337b2404e60ed58ed11
    container_name: minecraft
    environment:
      - UID=9001
      - GID=9001
      - EULA=TRUE
    volumes:
      - ./config:/config
      - ./worlds:/worlds
    security_opt:
      - no-new-privileges:true
    restart: 'unless-stopped'
    networks:
      default:
          ipv4_address: 192.168.94.70
networks:
  default:
    name: lan-network
    external: true