---
services:
  minecraft:
    image: ghcr.io/acbgbca/minecraft-bedrock:1.26.21.1@sha256:f22be2c38a4cf171d0e5452d5f32e0ff8571b0ea84843f01be6188cd07da893a
    container_name: minecraft
    environment:
      - UID=9001
      - GID=9001
      - EULA=TRUE
    volumes:
      - ./config:/config
      - ./worlds:/worlds
    security_opt:
      - no-new-privileges:true
    restart: 'unless-stopped'
    networks:
      default:
          ipv4_address: 192.168.94.70
networks:
  default:
    name: lan-network
    external: true