---
services:
  minecraft:
    image: ghcr.io/acbgbca/minecraft-bedrock:1.26.14.1@sha256:623028ce864a69f13b85135b9b8b784042c3a1e58f25a5a53a01347173157215
    container_name: minecraft
    environment:
      - UID=9001
      - GID=9001
      - EULA=TRUE
    volumes:
      - ./config:/config
      - ./worlds:/worlds
    security_opt:
      - no-new-privileges:true
    restart: 'unless-stopped'
    networks:
      default:
          ipv4_address: 192.168.94.70
networks:
  default:
    name: lan-network
    external: true