---
services:
  freshrss:
    image: freshrss/freshrss:1.29.0@sha256:cca8988d05cd449e1c6c69405971b1e6fc2c2116ceeb45c9fa3fc33837997a75
    container_name: freshrss
    labels:
      - traefik.enable=true
      - traefik.http.services.freshrss.loadbalancer.server.port=80
      - traefik.http.routers.freshrss.rule=Host(`freshrss.$DOMAIN`)
      - show.external=true
    environment:
      - TZ="Australia/Melbourne"
      - CRON_MIN=1,31
    volumes:
      - './data:/var/www/FreshRSS/data'
      - './extensions:/var/www/FreshRSS/extensions'
    restart: 'unless-stopped'
  rssbridge:
    image: rssbridge/rss-bridge@sha256:151826f65ef50a6e349b19ea1ff4874f26afb82638321328eec9d7b850bac620
    container_name: rssbridge
    environment:
      - CURL_IMPERSONATE=tor145
    labels:
      - traefik.enable=true
      - traefik.http.services.rssbridge.loadbalancer.server.port=80
      - show.external=true
    volumes:
      - ./bridge:/config
    restart: unless-stopped
    networks:
      default:
        aliases:
          - rssbridge.$DOMAIN # So I can copy and paste the URLs without needing to change the host
  playwrightproxy:
    image: ghcr.io/acbgbca/pw-scraper:0.211@sha256:b6c9af3001a521a2b2d94f7d0b2d602a224a50e8ae7acd9bbebee59b4daad3d6
    container_name: playwrightproxy
    environment:
      - LOG_LEVEL="debug"
    labels:
      - traefik.enable=true
      - traefik.http.services.playwrightproxy.loadbalancer.server.port=8080
      - show.external=true
    restart: unless-stopped
networks:
  default:
    external: true
    name: ctr-network