---
services:
  freshrss:
    image: freshrss/freshrss:1.29.1@sha256:ab6b363102ccdbc39f6a62db926f567c61a5289bf25ba460f1c34423d8cc1a4d
    container_name: freshrss
    labels:
      - traefik.enable=true
      - traefik.http.services.freshrss.loadbalancer.server.port=80
      - traefik.http.routers.freshrss.rule=Host(`freshrss.$DOMAIN`)
      - show.external=true
    environment:
      - TZ="Australia/Melbourne"
      - CRON_MIN=1,31
    volumes:
      - './data:/var/www/FreshRSS/data'
      - './extensions:/var/www/FreshRSS/extensions'
    restart: 'unless-stopped'
  rssbridge:
    image: rssbridge/rss-bridge@sha256:606896116558c57e3d381dec6874457f7a69216103d77c78b5bd38b92b251902
    container_name: rssbridge
    labels:
      - traefik.enable=true
      - traefik.http.services.rssbridge.loadbalancer.server.port=80
      - show.external=true
    volumes:
      - ./bridge:/config
    restart: unless-stopped
    networks:
      default:
        aliases:
          - rssbridge.$DOMAIN # So I can copy and paste the URLs without needing to change the host
  playwrightproxy:
    image: ghcr.io/acbgbca/pw-scraper:0.223@sha256:5f68dbc41c8db5a3dac500c456b9c41eaf2c377fed9e828865b34ce3aed6db0e
    container_name: playwrightproxy
    environment:
      - LOG_LEVEL="debug"
    labels:
      - traefik.enable=true
      - traefik.http.services.playwrightproxy.loadbalancer.server.port=8080
      - show.external=true
    restart: unless-stopped
  redlib:
    image: ghcr.io/itsjfx/redlib:latest@sha256:3f4d65903bf52b56f2f932e0140c822f58ec7511a54058ce1ad5b217ba1ed3bd
    container_name: redlib
    labels:
      - traefik.enable=true
      - traefik.http.services.redlib.loadbalancer.server.port=8080
      - show.external=true
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    env_file: redlib.env
    restart: unless-stopped
    networks:
      default:
        aliases:
          - redlib.$DOMAIN # So I can copy and paste the URLs without needing to change the host

networks:
  default:
    external: true
    name: ctr-network