---
services:
  freshrss:
    image: freshrss/freshrss:1.29.1@sha256:ab6b363102ccdbc39f6a62db926f567c61a5289bf25ba460f1c34423d8cc1a4d
    container_name: freshrss
    labels:
      - traefik.enable=true
      - traefik.http.services.freshrss.loadbalancer.server.port=80
      - traefik.http.routers.freshrss.rule=Host(`freshrss.$DOMAIN`)
      - show.external=true
    environment:
      - TZ="Australia/Melbourne"
      - CRON_MIN=1,31
    volumes:
      - './data:/var/www/FreshRSS/data'
      - './extensions:/var/www/FreshRSS/extensions'
    restart: 'unless-stopped'
  rssbridge:
    image: rssbridge/rss-bridge@sha256:2b61ee0effcbd07fabb0d566a6fae8daa68102ba3639d67baceb9f3ee6c6a829
    container_name: rssbridge
    labels:
      - traefik.enable=true
      - traefik.http.services.rssbridge.loadbalancer.server.port=80
      - show.external=true
    volumes:
      - ./bridge:/config
    restart: unless-stopped
    networks:
      default:
        aliases:
          - rssbridge.$DOMAIN # So I can copy and paste the URLs without needing to change the host
  playwrightproxy:
    image: ghcr.io/acbgbca/pw-scraper:0.213@sha256:66066bcc7d4538f40c734033519b256ac1e01295f8a54de5aa13a033dd1fddc2
    container_name: playwrightproxy
    environment:
      - LOG_LEVEL="debug"
    labels:
      - traefik.enable=true
      - traefik.http.services.playwrightproxy.loadbalancer.server.port=8080
      - show.external=true
    restart: unless-stopped
networks:
  default:
    external: true
    name: ctr-network