---
services:
  ittools:
    image: ghcr.io/sharevb/it-tools:latest@sha256:97bc20902dbe12f5d285ea2e14e9d44b5ea90588175c8c6959303c48b909d418
    container_name: ittools
    labels:
      - traefik.enable=true
      - traefik.http.services.ittools.loadbalancer.server.port=8080
      - show.external=true
    restart: 'unless-stopped'
networks:
  default:
    external: true
    name: ctr-network