---
services:
  ittools:
    image: ghcr.io/sharevb/it-tools:latest@sha256:e02954893ed0706cbd905571d7e68d09b722bba309d597b7135b7bdf0b6d418b
    container_name: ittools
    labels:
      - traefik.enable=true
      - traefik.http.services.ittools.loadbalancer.server.port=8080
      - show.external=true
    restart: 'unless-stopped'
networks:
  default:
    external: true
    name: ctr-network