---
services:
  ittools:
    image: ghcr.io/sharevb/it-tools:latest@sha256:0716f57e28344656c7a6212daccbaff1054d4d45138edf8d0a4ef14d3a3ca366
    container_name: ittools
    labels:
      - traefik.enable=true
      - traefik.http.services.ittools.loadbalancer.server.port=8080
      - show.external=true
    restart: 'unless-stopped'
networks:
  default:
    external: true
    name: ctr-network