services:
  ptv:
    image: ghcr.io/acbgbca/ptv-monitor:latest@sha256:a0bd1af4c877c8faf2b441660b670635aa0eddfb23792484945a439cff406562
    container_name: ptv
    user: 9001:9001
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.services.ptv.loadbalancer.server.port=8080
      - show.external=true
    volumes:
      - ./config.yaml:/config/config.yaml:ro
      - ./data:/data

networks:
  default:
    external: true
    name: ctr-network
